version: "3.9"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./dashboard-operator/Dockerfile
  #   container_name: cerdas-cermat-app
  #   working_dir: /var/www
  #   volumes:
  #     - ./dashboard-operator:/var/www
  #   ports:
  #     - "8000:8000"
  #     - "5173:5173"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   depends_on:
  #     - db
  #   command: bash -c "composer install && npm install && php artisan migrate  && php artisan serve --host=0.0.0.0 --port=8000"

  frankenphp:
    build:
      context: .
      dockerfile: ./dashboard-operator/Dockerfile.franken
    container_name: laravel-frankenphp
    ports:
      - "9090:80"
    volumes:
      - ./dashboard-operator:/app
    working_dir: /app
    environment:
      DOCUMENT_ROOT: /app/public
      CADDY_GLOBAL_OPTIONS: "auto_https off"
      SERVER_NAME: ":80"
      PHP_INI_DISPLAY_ERRORS: 1
      PHP_INI_DISPLAY_STARTUP_ERRORS: 1
      PHP_INI_ERROR_REPORTING: E_ALL
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # command: bash -c "composer install && npm install && npm run build"
  db:
    image: mysql:8.0
    container_name: cerdas-cermat-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cerdas_cermat
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  ws-server:
    image: node:20
    container_name: ws-server
    working_dir: /app
    ports:
      - "3003:3003"
    command: bash -c "npm install && node server.js"
    volumes:
      - ./ws-server:/app

  dashboard:
    image: node:20
    container_name: dashboard
    working_dir: /app
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./dashboard-score:/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  dbdata:
